#ifndef RTPTUN_H
#define RTPTUN_H

#define RTPTUN_TIMEOUT 120

#define RTPTUN_DEFAULT_SERVER_LISTEN "0.0.0.0"
#define RTPTUN_DEFAULT_SERVER_PORT "5004"

#define RTPTUN_DEFAULT_DEST_ADDR "127.0.0.1"
#define RTPTUN_DEFAULT_CLIENT_LISTEN "127.0.0.1"

#endif